// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChApRKJ4YFhh4UyImBrvNChg4jjUsGhdc',
    appId: '1:481556469515:web:9fcf2ed8f5eeeedc2f740e',
    messagingSenderId: '481556469515',
    projectId: 'e-commerce-9b8a1',
    authDomain: 'e-commerce-9b8a1.firebaseapp.com',
    storageBucket: 'e-commerce-9b8a1.appspot.com',
    measurementId: 'G-M6950F145S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw8fvDTzmPVoCs3CI3WVJ9BXNgN3nfpL4',
    appId: '1:481556469515:android:45a0a890d220d3ff2f740e',
    messagingSenderId: '481556469515',
    projectId: 'e-commerce-9b8a1',
    storageBucket: 'e-commerce-9b8a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJzFfKahAfLVK-dxWoYZDRzHt7NyIEICs',
    appId: '1:481556469515:ios:1e28aa6221ae99382f740e',
    messagingSenderId: '481556469515',
    projectId: 'e-commerce-9b8a1',
    storageBucket: 'e-commerce-9b8a1.appspot.com',
    iosClientId: '481556469515-qnuqkn85kpe54v1is0scpd2hdbmi1f3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJzFfKahAfLVK-dxWoYZDRzHt7NyIEICs',
    appId: '1:481556469515:ios:1e28aa6221ae99382f740e',
    messagingSenderId: '481556469515',
    projectId: 'e-commerce-9b8a1',
    storageBucket: 'e-commerce-9b8a1.appspot.com',
    iosClientId: '481556469515-qnuqkn85kpe54v1is0scpd2hdbmi1f3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
